samples/Vogen.Examples/Vogen.Examples.csproj, src/Vogen.SharedTypes/InstanceAttribute.cs, src/Vogen/BuildWorkItems.cs, src/Vogen/InstanceProperties.cs, src/Vogen/Util.cs, tests/Testbench/Program.cs, tests/Vogen.IntegrationTests/SnapshotTests/SnapshotTest.cs, tests/Vogen.IntegrationTests/SnapshotTests/Snapshots/ValueObjectGeneratorTests.Produces_instances.verified.txt, tests/Vogen.IntegrationTests/Vogen.IntegrationTests.csproj, tests/Vogen.Tests/Vogen.Tests.csproj
Can now add a `tripleSlashComment` argument to the `Instance` attribute for comments that show in intellisense.
Fixes #44
=> Comments for `Instance` attribute

README.md, src/Vogen/Analyzers/CreationUsingReflectionAnalyzer.cs, src/Vogen/Diagnostics/DiagnosticCode.cs, src/Vogen/Diagnostics/DiagnosticItems.cs, tests/SmallTests/DiagnosticsTests/DisallowCreationWithReflectionTests.cs, tests/SmallTests/DiagnosticsTests/DisallowDefaultingTests.cs, tests/SmallTests/DiagnosticsTests/LocalConfig/HappyTests.cs, tests/SmallTests/DiagnosticsTests/LocalConfig/SadTests.cs, tests/SmallTests/DiagnosticsTests/NormalizeInputMethodTests.cs, tests/SmallTests/DiagnosticsTests/ProhibitPrimaryConstructorTests.cs, tests/SmallTests/RecordClassCreationTests.cs, tests/SmallTests/RecordStructCreationTests.cs, tests/Testbench/Program.cs
The purpose of this change is to phohibit creation using `Activator.CreateInstance`.
Creating Value Objects with Reflection evades the validation mechanism, allowing invalid Value Objects to be live in the domain of the application.
For instance, with this Value Object:
```csharp
[ValueObject]
public partical struct CustomerId {{ }}
```
It disallows this:
```csharp
// result in error VOG025: Type 'CustomerId' cannot be constructed via Reflection as it 
var c = Activator.CreateInstance<CustomerId>(); is prohibited.
```
and...
```csharp
// result in error VOG025: Type 'CustomerId' cannot be constructed via Reflection as it 
var c = (CustomerId)Activator.CreateInstance(); 
```
=> Prohibit reflection with Activator.CreateInstance

src/Vogen.SharedTypes/DebuggerAttributeGeneration.cs, src/Vogen.SharedTypes/ValueObjectAttribute.cs, src/Vogen.SharedTypes/VogenDefaultsAttribute.cs, src/Vogen/BuildWorkItems.cs, src/Vogen/ManageAttributes.cs, src/Vogen/Util.cs, src/Vogen/VoWorkItem.cs, src/Vogen/VogenConfiguration.cs, tests/SnapshotTests/Config/GlobalConfigTests.cs, tests/SnapshotTests/Config/LocalConfigTests.cs, tests/SnapshotTests/Config/snapshots/snap-v3.1/GlobalConfigTests.OmitDebugAttributes_override.verified.txt, tests/SnapshotTests/Config/snapshots/snap-v3.1/LocalConfigTests.OmitDebugAttributes_override.verified.txt, tests/SnapshotTests/Config/snapshots/snap-v4.6.1/GlobalConfigTests.OmitDebugAttributes_override.verified.txt, tests/SnapshotTests/Config/snapshots/snap-v4.6.1/LocalConfigTests.OmitDebugAttributes_override.verified.txt, tests/SnapshotTests/Config/snapshots/snap-v4.8/GlobalConfigTests.OmitDebugAttributes_override.verified.txt, tests/SnapshotTests/Config/snapshots/snap-v4.8/LocalConfigTests.OmitDebugAttributes_override.verified.txt, tests/SnapshotTests/Config/snapshots/snap-v5.0/GlobalConfigTests.OmitDebugAttributes_override.verified.txt, tests/SnapshotTests/Config/snapshots/snap-v5.0/LocalConfigTests.OmitDebugAttributes_override.verified.txt, tests/SnapshotTests/Config/snapshots/snap-v6.0/GlobalConfigTests.OmitDebugAttributes_override.verified.txt, tests/SnapshotTests/Config/snapshots/snap-v6.0/LocalConfigTests.OmitDebugAttributes_override.verified.txt, tests/SnapshotTests/Config/snapshots/snap-v7.0/GlobalConfigTests.OmitDebugAttributes_override.verified.txt, tests/SnapshotTests/Config/snapshots/snap-v7.0/LocalConfigTests.OmitDebugAttributes_override.verified.txt, tests/SnapshotTests/SnapshotRunner.cs, tests/Vogen.Tests/VogenConfigurationTests.cs
Fixes https://github.com/SteveDunn/Vogen/issues/341
The way this was oringally implemented couldn't work: it declared as a `bool` which means when it comes to merging (the bit that says it's going to prefer local (`ValueObject`) attributes over global (`VogenDefaults`)), it's not going to know which to pick as both flags _need_ to be set.
It really needed to be a `bool?`. This way, merging would know whether or not it was specified locally and/or globally.
But nullable bools can't be parameters on an attribute.
An attribute is used instead which allows us to default the values so that merging can _really_ see when the user has overridden the defaults.
=> Fixes issue where flag for omitting debug attributes was ignored

README.md, src/Vogen/ManageAttributes.cs, tests/SnapshotTests/GenericAttributeTests.cs, tests/SnapshotTests/snapshots/snap-v7.0/GenericAttributeTests.Produces_instances_with_derived_attribute.verified.txt
This PR aims to fix an issue introduced in #321 (reported by @glen-84 in comments) where derived attributes failed to extract parameters/generic types. This was caused by the configuration builder getting generic type arguments from the attribute class without also looking at the base class - as well as my own lack of understand on how Vogen extracted data from attributes (e.g. conversions).
As part of this fix I've also modified the test that produced a false positive to cover both non-`int` types and custom parameters. The `README` has also been updated to highlight that constructors of derived attributes need to have the defaults in their constructor, not the base constructor.
=> fix: extract constructor parameters & generic type info form derived attributes

README.md
I forked and looked for a way to implement normalization before founding it already implemented in source code.
=> Make normalization easier to discover

tests/SnapshotTests/SnapshotTests.csproj
These occur due to a bug in VS where it incorrectly duplicates dynamic includes when you copy/rename a test file.
=> Remove redundant verified includes

src/Vogen/VoFilter.cs, tests/AnalyzerTests/DoNotUseNewAnalyzerTests.cs
This solves the bug reported in: https://github.com/SteveDunn/Vogen/issues/389
The issue was that the VoFilter didn't match the generic ValueObjectAttribute FullName.
I also created a test case based on an existing to verify that the issue is fixed
=> fixed issue with VoFilter not matching the generic ValueObjectAttribute

tests/Vogen.Tests/InstanceGenerationTests.cs
When running locally I had a few test cases breaking as we use ',' as the decimal separator in Denmark.
I fixed the test cases by using FormattableString.Invariant() for the expected input
=> Use FormattableString.Invariant in culture dependent tests

src/Vogen/Templates/AnyOtherType/AnyOtherType_NewtonsoftJsonConverterReferenceType.cs
Vogen does not follow best practices for null checks. Instead of using the "is" operator, it is using equality operators. This sometimes causes issues when a class has overloaded the equality operators.
Consider this code:
```
[ValueObject(typeof(String))]
public partial class LinuxAbsoluteFilename: IAbsoluteFilename
{
public static Boolean operator ==(LinuxAbsoluteFilename? Left, IAbsoluteFilename? Right);
public static Boolean operator !=(LinuxAbsoluteFilename? Left, IAbsoluteFilename? Right);
}
[ValueObject(typeof(LinuxAbsoluteFilename), conversions: Conversions.NewtonsoftJson)]
public sealed partial class AbsoluteContainerFilename
{
}
```
When using the Newtonsoft converter, the generated code by Vogen looks like:
```
var result = serializer.Deserialize<LinuxAbsoluteFilename>(reader); …
```
=> Use 'is not null' instead of '!= null' in Newtonsoft converter

src/Vogen/GenerateCodeForParse.cs
The word "method" is repeated in a doc comment in `GenerateCodeForParse.cs`. It makes ReSharper sad.
=> Typo in doc comment

src/Vogen/GenerateCastingOperators.cs, tests/ConsumerTests/BugFix624.cs, tests/ConsumerTests/Casting/ForClasses.cs, tests/ConsumerTests/Casting/ForStructs.cs, tests/ConsumerTests/Casting/Types.cs
The code is updated to integrate support for normalization when casting implicitly. During this implicit casting process, the 'NormalizeInput' method is now called if it is available in the respective class. Corresponding test cases have been added to validate this behavior.
=> Implicit casts from the primitive now call the `NormalizeInput` method if one is provided

samples/Vogen.Examples/SerializationAndConversion/Mongo/MongoScenario.cs, src/Vogen/AnalyzerReleases.Shipped.md, src/Vogen/Diagnostics/RuleIdentifiers.cs, src/Vogen/Rules/DoNotThrowFromUserCodeAnalyzer.cs, tests/AnalyzerTests/DoNotThrowFromUserCodeAnalyzerTests.cs
=> Add analyzer to check for for user throw keywords in NormalizeInput and Validate

src/Vogen/Suppressors/CA1036ComparisonSuppressor.cs, tests/AnalyzerTests/CA1036SuppressionTests.cs
=> Add CA1036 Suppressor

tests/AnalyzerTests/AnalyzerTests.csproj, tests/Shared/Shared.csproj, tests/SnapshotTests/SnapshotTests.csproj
RunSnapshots.ps1 is currently blocked by a warning-as-error due to https://github.com/dotnet/announcements/issues/312. The package is transitively referenced and it doesn't seem the NuGets on the path will receive any updates any time soon, so explicitly overriding the version is the only thing that can be done.
=> Explicitly override System.Formats.Asn1 

src/Vogen.CodeFixers/Rules/MakeStructReadonlyFixers/MakeStructReadonlyCodeFixProvider.cs, src/Vogen/AnalyzerReleases.Unshipped.md, src/Vogen/Diagnostics/RuleIdentifiers.cs, src/Vogen/Rules/PreferReadonlyStructAnalyzer.cs, tests/AnalyzerTests/PreferReadonlyStructsAnalyzerTests.cs
New feature to enforce the use of `readonly` structs in C# code. #603 
Introduces a new code fix provider and analyzer to ensure structs are marked as `readonly` when appropriate.
- `MakeStructReadonlyCodeFixProvider.cs`: Added a new `CodeFixProvider` to apply the `readonly` modifier to structs.
- `AnalyzerReleases.Unshipped.md`: Added rule entry `VOG033` for the new analyzer.
- `RuleIdentifiers.cs`: Added constant `UseReadonlyStructInsteadOfStruct` for rule `VOG033`.
- `PreferReadonlyStructAnalyzer.cs`: Added a new `DiagnosticAnalyzer` to report diagnostics for non-`readonly` structs.
- `PreferReadonlyStructsAnalyzerTests.cs`: Added tests to verify the analyzer's behavior.
=> Prefer readonly struct analyzer and codefix

tests/ConsumerTests/ParsingAndFormattingTests/TryFormatTests.cs, tests/ConsumerTests/ToStringTests/BasicFunctionality.cs
This PR removes culture dependency of two consumer unit tests.
=> Use invariant culture in unit test string comparison

docs/site/Writerside/topics/discussions/Home.md
Happened to see it when I was reading through.
=> Fix typo in example on home page

src/Vogen.SharedTypes/Vogen.SharedTypes.csproj
The issue here was that although you have the private key with which to sign, the build wasn't using it.
`PublicSign=true` tells the build to _not_ sign the assembly, but merely give it the strong name. This is fine for .NET but breaks in certain scenarios on .NET Framework.
Fixes #761
=> Fix invalid strong name on assembly

samples/Vogen.Examples/TypicalScenarios/Instances.cs, src/Vogen/Rules/DoNotUseNewAnalyzer.cs, tests/AnalyzerTests/DoNotUseNewAnalyzerTests.cs
Fixes #787
Relaxes VOG010 slightly so that instances can also be static properties without a setter (init is already disallowed on static properties).
This supports design guidelines that prefer to use properties over fields for public members.
=> Allows instances to be static getter properties

README.md
I've just got a 404 trying to navigate to that wiki page from README, so I'd like to correct the URL.
=> correct the link to normalization wiki page
